<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.4
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */
?>
<div class="row all-seller-cont">
    <?php
            $countries = array
            (
                'AF' => 'Afghanistan',
                'AX' => 'Aland Islands',
                'AL' => 'Albania',
                'DZ' => 'Algeria',
                'AS' => 'American Samoa',
                'AD' => 'Andorra',
                'AO' => 'Angola',
                'AI' => 'Anguilla',
                'AQ' => 'Antarctica',
                'AG' => 'Antigua And Barbuda',
                'AR' => 'Argentina',
                'AM' => 'Armenia',
                'AW' => 'Aruba',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'AZ' => 'Azerbaijan',
                'BS' => 'Bahamas',
                'BH' => 'Bahrain',
                'BD' => 'Bangladesh',
                'BB' => 'Barbados',
                'BY' => 'Belarus',
                'BE' => 'Belgium',
                'BZ' => 'Belize',
                'BJ' => 'Benin',
                'BM' => 'Bermuda',
                'BT' => 'Bhutan',
                'BO' => 'Bolivia',
                'BA' => 'Bosnia And Herzegovina',
                'BW' => 'Botswana',
                'BV' => 'Bouvet Island',
                'BR' => 'Brazil',
                'IO' => 'British Indian Ocean Territory',
                'BN' => 'Brunei Darussalam',
                'BG' => 'Bulgaria',
                'BF' => 'Burkina Faso',
                'BI' => 'Burundi',
                'KH' => 'Cambodia',
                'CM' => 'Cameroon',
                'CA' => 'Canada',
                'CV' => 'Cape Verde',
                'KY' => 'Cayman Islands',
                'CF' => 'Central African Republic',
                'TD' => 'Chad',
                'CL' => 'Chile',
                'CN' => 'China',
                'CX' => 'Christmas Island',
                'CC' => 'Cocos (Keeling) Islands',
                'CO' => 'Colombia',
                'KM' => 'Comoros',
                'CG' => 'Congo',
                'CD' => 'Congo, Democratic Republic',
                'CK' => 'Cook Islands',
                'CR' => 'Costa Rica',
                'CI' => 'Cote D\'Ivoire',
                'HR' => 'Croatia',
                'CU' => 'Cuba',
                'CY' => 'Cyprus',
                'CZ' => 'Czech Republic',
                'DK' => 'Denmark',
                'DJ' => 'Djibouti',
                'DM' => 'Dominica',
                'DO' => 'Dominican Republic',
                'EC' => 'Ecuador',
                'EG' => 'Egypt',
                'SV' => 'El Salvador',
                'GQ' => 'Equatorial Guinea',
                'ER' => 'Eritrea',
                'EE' => 'Estonia',
                'ET' => 'Ethiopia',
                'FK' => 'Falkland Islands (Malvinas)',
                'FO' => 'Faroe Islands',
                'FJ' => 'Fiji',
                'FI' => 'Finland',
                'FR' => 'France',
                'GF' => 'French Guiana',
                'PF' => 'French Polynesia',
                'TF' => 'French Southern Territories',
                'GA' => 'Gabon',
                'GM' => 'Gambia',
                'GE' => 'Georgia',
                'DE' => 'Germany',
                'GH' => 'Ghana',
                'GI' => 'Gibraltar',
                'GR' => 'Greece',
                'GL' => 'Greenland',
                'GD' => 'Grenada',
                'GP' => 'Guadeloupe',
                'GU' => 'Guam',
                'GT' => 'Guatemala',
                'GG' => 'Guernsey',
                'GN' => 'Guinea',
                'GW' => 'Guinea-Bissau',
                'GY' => 'Guyana',
                'HT' => 'Haiti',
                'HM' => 'Heard Island & Mcdonald Islands',
                'VA' => 'Holy See (Vatican City State)',
                'HN' => 'Honduras',
                'HK' => 'Hong Kong',
                'HU' => 'Hungary',
                'IS' => 'Iceland',
                'IN' => 'India',
                'ID' => 'Indonesia',
                'IR' => 'Iran, Islamic Republic Of',
                'IQ' => 'Iraq',
                'IE' => 'Ireland',
                'IM' => 'Isle Of Man',
                'IL' => 'Israel',
                'IT' => 'Italy',
                'JM' => 'Jamaica',
                'JP' => 'Japan',
                'JE' => 'Jersey',
                'JO' => 'Jordan',
                'KZ' => 'Kazakhstan',
                'KE' => 'Kenya',
                'KI' => 'Kiribati',
                'KR' => 'Korea',
                'KW' => 'Kuwait',
                'KG' => 'Kyrgyzstan',
                'LA' => 'Lao People\'s Democratic Republic',
                'LV' => 'Latvia',
                'LB' => 'Lebanon',
                'LS' => 'Lesotho',
                'LR' => 'Liberia',
                'LY' => 'Libyan Arab Jamahiriya',
                'LI' => 'Liechtenstein',
                'LT' => 'Lithuania',
                'LU' => 'Luxembourg',
                'MO' => 'Macao',
                'MK' => 'Macedonia',
                'MG' => 'Madagascar',
                'MW' => 'Malawi',
                'MY' => 'Malaysia',
                'MV' => 'Maldives',
                'ML' => 'Mali',
                'MT' => 'Malta',
                'MH' => 'Marshall Islands',
                'MQ' => 'Martinique',
                'MR' => 'Mauritania',
                'MU' => 'Mauritius',
                'YT' => 'Mayotte',
                'MX' => 'Mexico',
                'FM' => 'Micronesia, Federated States Of',
                'MD' => 'Moldova',
                'MC' => 'Monaco',
                'MN' => 'Mongolia',
                'ME' => 'Montenegro',
                'MS' => 'Montserrat',
                'MA' => 'Morocco',
                'MZ' => 'Mozambique',
                'MM' => 'Myanmar',
                'NA' => 'Namibia',
                'NR' => 'Nauru',
                'NP' => 'Nepal',
                'NL' => 'Netherlands',
                'AN' => 'Netherlands Antilles',
                'NC' => 'New Caledonia',
                'NZ' => 'New Zealand',
                'NI' => 'Nicaragua',
                'NE' => 'Niger',
                'NG' => 'Nigeria',
                'NU' => 'Niue',
                'NF' => 'Norfolk Island',
                'MP' => 'Northern Mariana Islands',
                'NO' => 'Norway',
                'OM' => 'Oman',
                'PK' => 'Pakistan',
                'PW' => 'Palau',
                'PS' => 'Palestinian Territory, Occupied',
                'PA' => 'Panama',
                'PG' => 'Papua New Guinea',
                'PY' => 'Paraguay',
                'PE' => 'Peru',
                'PH' => 'Philippines',
                'PN' => 'Pitcairn',
                'PL' => 'Poland',
                'PT' => 'Portugal',
                'PR' => 'Puerto Rico',
                'QA' => 'Qatar',
                'RE' => 'Reunion',
                'RO' => 'Romania',
                'RU' => 'Russia',
                'RW' => 'Rwanda',
                'BL' => 'Saint Barthelemy',
                'SH' => 'Saint Helena',
                'KN' => 'Saint Kitts And Nevis',
                'LC' => 'Saint Lucia',
                'MF' => 'Saint Martin',
                'PM' => 'Saint Pierre And Miquelon',
                'VC' => 'Saint Vincent And Grenadines',
                'WS' => 'Samoa',
                'SM' => 'San Marino',
                'ST' => 'Sao Tome And Principe',
                'SA' => 'Saudi Arabia',
                'SN' => 'Senegal',
                'RS' => 'Serbia',
                'SC' => 'Seychelles',
                'SL' => 'Sierra Leone',
                'SG' => 'Singapore',
                'SK' => 'Slovakia',
                'SI' => 'Slovenia',
                'SB' => 'Solomon Islands',
                'SO' => 'Somalia',
                'ZA' => 'South Africa',
                'GS' => 'South Georgia And Sandwich Isl.',
                'ES' => 'Spain',
                'LK' => 'Sri Lanka',
                'SD' => 'Sudan',
                'SR' => 'Suriname',
                'SJ' => 'Svalbard And Jan Mayen',
                'SZ' => 'Swaziland',
                'SE' => 'Sweden',
                'CH' => 'Switzerland',
                'SY' => 'Syrian Arab Republic',
                'TW' => 'Taiwan',
                'TJ' => 'Tajikistan',
                'TZ' => 'Tanzania',
                'TH' => 'Thailand',
                'TL' => 'Timor-Leste',
                'TG' => 'Togo',
                'TK' => 'Tokelau',
                'TO' => 'Tonga',
                'TT' => 'Trinidad And Tobago',
                'TN' => 'Tunisia',
                'TR' => 'Turkey',
                'TM' => 'Turkmenistan',
                'TC' => 'Turks And Caicos Islands',
                'TV' => 'Tuvalu',
                'UG' => 'Uganda',
                'UA' => 'Ukraine',
                'AE' => 'United Arab Emirates',
                'GB' => 'United Kingdom',
                'US' => 'United States',
                'UM' => 'United States Outlying Islands',
                'UY' => 'Uruguay',
                'UZ' => 'Uzbekistan',
                'VU' => 'Vanuatu',
                'VE' => 'Venezuela',
                'VN' => 'Viet Nam',
                'VG' => 'Virgin Islands, British',
                'VI' => 'Virgin Islands, U.S.',
                'WF' => 'Wallis And Futuna',
                'EH' => 'Western Sahara',
                'YE' => 'Yemen',
                'ZM' => 'Zambia',
                'ZW' => 'Zimbabwe',
            );

    ?>
    <div class="col-md-3">
        <?php  $seller_collection_n = Mage::getModel('marketplace/sellerprofile')->getCollection()->setOrder('store_title','ASC') ;
                $countrys = $this->getRequest()->getParam('country')   ;
                $states = $this->getRequest()->getParam('state')   ;
        ?>
        <div class="countries_list">
            <ul class="countries_list_cont1">
                <?php
                $countrys = $this->getRequest()->getParam('country')   ;
                $states = $this->getRequest()->getParam('state')   ;
                ?>
                <?php if( !empty($countrys)):  ?>
                    <li class="get_cont"><span class="get_country"> > Country</span> <span class="get_country_name"><?php echo $countries[$countrys]?></span></li>
                <?php endif;?>
                 <?php if( !empty($states)):  ?>
                     <li  class="get_cont"><span class="get_country"> > City</span> <span class="get_country_name"><?php echo $states?></span></li>
                 <?php endif;?>
                <?php if( !empty($countrys)):  ?>
                    <li  class="get_cont get_cont_dell"> <a href="http://148.251.126.204/~grotto/index.php/marketplace/seller/allseller/">Clear All</a></li>
                <?php endif;?>

                <li class="countries_list_title"><span>STUDIO LOCATION</span><i class="fa fa-minus"></i></li>
                <li class="countries_list_dropdown">
                    <ul class="countries_list_cont">
                        <?php
                             $countries_state = array();
                             $states = array();
                            foreach ($seller_collection_n as $seller_coll) {

                                $seller_id_n = $seller_coll['seller_id'];
                                $sellerPage_n = Mage::getModel('marketplace/sellerprofile')->collectprofile($seller_id_n);
                                $sell_country = $sellerPage_n['country'];
                                $sell_state = $sellerPage_n['state'];
                                if (array_key_exists($sell_country, $countries_state)) {
                                    // array_push($states,$countries_state[$sell_country],$sell_state);
                                    //$countries_state[$sell_country]=$states;
                                    if (!empty($sell_state)) {
                                        $countries_state[$sell_country] = $countries_state[$sell_country]."+".$sell_state;
                                    }
                                } else {
                                    $countries_state[$sell_country] = $sell_state;
                                }
                            }
                              foreach ($countries_state as $key=>$val):
                            ?>
                            <li class="countries_list_item">
                                <span>|</span>
                                <a class="countries_list_link" href="?country=<?php echo $key;?>">
                                    <?php echo $countries[$key];?>
                                </a>
                                <i class="fa fa-plus"></i>
                                <ul class="state_list_dropdown">
                                    <?php $st = explode("+",$val);
                                     foreach ($st as $vals):   ?>
                                        <li><a href="?country=<?php echo $key;?>&state=<?php echo $vals;?>"><?php echo $vals;?></a></li>
                                      <?php endforeach;?>
                                </ul>
                            </li>
                        <?php endforeach;?>
                    </ul>
                </li>
            </ul>

                    <script>
                        $j(document).ready(function($){
                            var alphabets = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"];
                            var fletter='';
                            alphabets.forEach(function(e) {
                                fletter= e.toLowerCase();
                                $('.first_letter_'+fletter).eq(0).addClass("active_first_letter")
                            });
                            $(".alfabetical_list_title i").click(function(){
                                $(this).toggleClass("fa-minus fa-plus");
                                $(".alfabetical_list_dropdown").slideToggle();
                            })
                             $(".countries_list_title i").click(function(){
                                 $(this).toggleClass("fa-minus fa-plus");
                                 $(".countries_list_dropdown").slideToggle();
                             })
                               $(".countries_list_item i").click(function(){
                                   $(this).toggleClass("fa-minus fa-plus");
                                   $(this).next().slideToggle();
                               })


                        })

                    </script>

        </div>
        <div class="alfabetical_list">
            <ul class="alfabetical_list_cont1">
                <li class="alfabetical_list_title"><span>A-Z</span><i class="fa fa-minus"></i></li>
                <li class="alfabetical_list_dropdown">
                    <ul class="alfabetical_list_cont">
                        <?php foreach ($seller_collection_n as $seller_collection_n): ?>
                            <?php   $seller_id_n = $seller_collection_n['seller_id'];
                            $get_requestPath_n = Mage::helper('marketplace/marketplace')->getSellerRewriteUrl($seller_id_n);
                            $store_title =trim($seller_collection_n['store_title']); ?>
                            <li class="alfabetical_list_item">
                                <span>|</span>
                                <a class="alfabetical_list_link first_letter_<?php echo lcfirst($store_title[0]);?>" href="<?php echo $get_requestPath_n;?>">
                                    <?php echo  $store_title;?>
                                </a>
                            </li>
                        <?php endforeach;?>
                    </ul>
                </li>
            </ul>

         </div>
    </div>
    <div class="col-md-9">
      <!--  <div class="page-title">
            <h1><?php /*echo $this->__('All sellers'); */?> </h1>
        </div>-->
         <?php
            //Get seller data collection
              $countrys = $this->getRequest()->getParam('country')   ;
              $states = $this->getRequest()->getParam('state')   ;
         if( !empty($countrys))  {
              $seller_collection = Mage::getModel('marketplace/sellerprofile')->getCollection()->addFilter('country', $countrys)->setOrder('store_title','ASC');
            if( !empty($states)){
                    $seller_collection = Mage::getModel('marketplace/sellerprofile')->getCollection()->addFilter('country', $countrys)->addFilter('state', $states)->setOrder('store_title','ASC');
            }
         }  else{
                  $seller_collection = Mage::getModel('marketplace/sellerprofile')->getCollection()->setOrder('store_title','ASC');
         }

            $seller_count = count($seller_collection);

         if ($seller_count > 0) { ?>
         <div class="my-account-wrapper">
             <!--<ul class="mp_all_sellers_container f-left" border="0" cellspacing="0" cellpadding="0">-->
             <ul class="mp_all_sell_cont">
           <?php
                foreach ($seller_collection as $_seller_collection) {
                    $seller_id = $_seller_collection['seller_id'];
                    $get_requestPath = Mage::helper('marketplace/marketplace')->getSellerRewriteUrl($seller_id);
                    $sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($seller_id);
                    if (strpos($_seller_collection['store_logo'], '.') && $_seller_collection['store_title'] != '') {
                        ?>
                        <li class="f-left col-md-4">
                            <a class="mp_all_sellers_views" href="<?php echo $get_requestPath; ?>"
                            title="<?php echo $_seller_collection['store_title']; ?>">
                            <img  width="100%" src="<?php echo Mage::getBaseUrl('media') . "marketplace/resized/" . $_seller_collection['store_logo']; ?>" style="vertical-align: middle;" />
                            </a>
                            <h4 class="sell-name" ><?php echo $_seller_collection['store_title']; ?></h4>
                            <h5 class="sell-cost-name"><?php if(!empty($_seller_collection['state'])): ?><span><?php echo $_seller_collection['state'];?></span>, <?php endif;?><span><?php echo $countries[$_seller_collection['country']];?></span></h5>
                        </li>
                <?php }
                if (!strpos($_seller_collection['store_logo'], '.') && $_seller_collection['store_title'] != '') { ?>
                        <li class="f-left col-md-4">
                            <a class="mp_all_sellers_views" href="<?php echo $get_requestPath; ?>"
                            title="<?php echo $_seller_collection['store_title']; ?>">
                                <img width="100%"  src="<?php echo $this->getSkinUrl('images/no-store-logo.png'); ?>" style="vertical-align: middle;" />
                            </a>
                            <h4 class="sell-name"><?php echo $_seller_collection['store_title']; ?></h4>
                            <h5 class="sell-cost-name"><?php if(!empty($_seller_collection['state'])): ?><span><?php echo $_seller_collection['state'];?></span>, <?php endif;?><span><?php echo $countries[$_seller_collection['country']];?></span></h5>
                        </li>
                <?php }

            } ?>
            </ul>
            </div>
            <div style="clear: both;"></div>
            <?php
           // echo $this->getPagerHtml();
        } else {
            echo $this->__('There is no seller available.');
        }
        ?>
     </div>
</div>