<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            <div class="clearfix">
                <div class="pull-left postDetails">
                    <?php if ($this->getCommentsEnabled()): ?>
                        <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
                    <?php endif; ?>
                    <?php $postCats = $post->getCats(); ?>
                    <?php if (!empty($postCats)): ?>
                        <?php echo Mage::helper('blog')->__('Posted in'); ?>
                        <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php echo Mage::helper('blog')->__('Posted'); ?>
                    <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
                </div>
                <h3 class="pull-right postTime"><?php echo $post->getCreatedTime(); ?></h3>
            </div>
        </div>
        <div class="postContent std"><?php echo $post->getPostContent(); ?></div>

        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>

    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
