<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.6
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */?>
 
<?php 
/**
 * Get infromatin through posted values like
 * id
 * customer data
 * vacation mode
 * vacation status val
 */
$id = $this->getRequest()->getParam('id');
$customerData = Mage::getModel('customer/customer')->load($id);
$vacationMode = Mage::getModel('marketplace/vacationmode')->load($id,'seller_id');
$vacationStatusVal = $vacationMode->getVacationStatus();
/**
 * display product collection
 * Get seller page
 * current data
 * current url
 */
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
$currentDate = Mage::getModel('core/date')->date('Y-m-d');
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$countries = array
(
    'AF' => 'Afghanistan',
    'AX' => 'Aland Islands',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctica',
    'AG' => 'Antigua And Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia And Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CV' => 'Cape Verde',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos (Keeling) Islands',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CG' => 'Congo',
    'CD' => 'Congo, Democratic Republic',
    'CK' => 'Cook Islands',
    'CR' => 'Costa Rica',
    'CI' => 'Cote D\'Ivoire',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands (Malvinas)',
    'FO' => 'Faroe Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French Southern Territories',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard Island & Mcdonald Islands',
    'VA' => 'Holy See (Vatican City State)',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran, Islamic Republic Of',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IM' => 'Isle Of Man',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'KR' => 'Korea',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Lao People\'s Democratic Republic',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libyan Arab Jamahiriya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MK' => 'Macedonia',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia, Federated States Of',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'AN' => 'Netherlands Antilles',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinian Territory, Occupied',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines',
    'PN' => 'Pitcairn',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RE' => 'Reunion',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'RW' => 'Rwanda',
    'BL' => 'Saint Barthelemy',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts And Nevis',
    'LC' => 'Saint Lucia',
    'MF' => 'Saint Martin',
    'PM' => 'Saint Pierre And Miquelon',
    'VC' => 'Saint Vincent And Grenadines',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome And Principe',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'South Georgia And Sandwich Isl.',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard And Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syrian Arab Republic',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Thailand',
    'TL' => 'Timor-Leste',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad And Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks And Caicos Islands',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'US' => 'United States',
    'UM' => 'United States Outlying Islands',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VE' => 'Venezuela',
    'VN' => 'Viet Nam',
    'VG' => 'Virgin Islands, British',
    'VI' => 'Virgin Islands, U.S.',
    'WF' => 'Wallis And Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
);
?>
<?php if (strpos($sellerPage->getStoreBanner(), '.')) { ?>
    <?php $banner_img = Mage::getBaseUrl('media') . "marketplace/resized/" . $sellerPage->getStoreBanner(); ?>
<?php } else { ?>
    <?php $banner_img = $this->getSkinUrl('images/no-banner-image.png'); ?>
<?php  } ?>
<div class="market_place_profile" style="background-image:url(<?php echo $banner_img;?>)">

   <div class="markeft_place_main_widget">
  <?php if ($vacationStatusVal==0){
      /**
       * If vation status value is equal to 0
       * then get the vacation message data
       */
  $vacationMessageData = $vacationMode->getVacationMessage();
  /**
   * Check the vation message data is not empty
   * if so then display the vacation message
   */
  if (!empty($vacationMessageData)){
  ?>
  <h1><marquee><?php echo $vacationMessageData; ?></marquee></h1>
  <?php }
  } ?>
<?php
/**
 * Face book Like Button Script
 */
$sellCountry = $sellerPage->getCountry();
$sellState = $sellerPage->getState();

?>

       <div id="fb-root"></div>
        <!--display seller logo-->
        <div class="mp_profiles_container" style="display:none">
        <div class="seller_store_banner" >
         <p class="mp_profiles_banner">
                    <?php if (strpos($sellerPage->getStoreBanner(), '.')) { ?>
                        <img src="<?php echo Mage::getBaseUrl('media') . "marketplace/resized/" . $sellerPage->getStoreBanner(); ?>" alt="store banner" class="market_place_store_img_banner" width="1100" height="232" />
                    <?php } else { ?>
                    <img src="<?php echo $this->getSkinUrl('images/no-banner-image.png'); ?>" alt="store banner" class="market_place_store_img_banner" />
                   <?php  } ?>
                </p>
                </div>
               <div class="mp_profiles-info-wrapper"> <p class="mp_profiles_logo">
                    <?php if (strpos($sellerPage->getStoreLogo(), '.')) { ?>
                        <img src="<?php echo Mage::getBaseUrl('media') . "marketplace/resized/" . $sellerPage->getStoreLogo(); ?>" alt="store logo" class="market_place_store_img" />
                    <?php } else { ?>
                      <img src="<?php echo $this->getSkinUrl('images/no-store-logo.png'); ?>" alt="store logo" class="market_place_store_img" />
                        <?php } ?>
                </p>
                <div class="dddd sellers_store_info">
                     <div class="contact-wrapper">
                 <span class="contact-number"><a><?php
                  echo $sellerPage->getContact();?></a></span>
                 <span class="contact-mail"><a href="mailto:<?php echo $customerData->getEmail();?>"><?php
                  echo $customerData->getEmail();?></a></span>
                 </div>
                <?php
                /**
                 * Display Seller address information like
                 * seller store title
                 * seller store state
                 * seller store country
                 */?>
                 <h2><?php echo $sellerPage->getStoreTitle();?></h2>
                <address>
                 <?php echo $sellerPage->getStoreState();?>
                 <?php echo $sellerPage->getStoreCountry();?>
                 </address>
                 <?php
                 /**
                  * Display Ratings
                  * if the review count is greater than zero
                  * then calcualte the ratings average
                  * and display the ratings average
                  */
                 ?>
                 <?php if (Mage::getStoreConfig('marketplace/seller_review/enable_review')) { ?>
                <span class="all_review_container_wr">
                                <h3><?php echo $this->__('Average Ratings'); ?></h3>
                                <?php $reviewCount = $this->reviewCount($id);?>
                                 <?php if($reviewCount>0){?>
                                <span class="all_reviews_details_wr">
                                    <p class="all_reviews_block">
                                        <?php
                                        $ratingCollection = $this->averageRatings($id);
                                        ?>
                                        <label class="all_review_rating" style="width:<?php echo round($ratingCollection,1) * 20; ?>%;"></label>
                                    </p>
                                </span>
                                <p class="rating_s"><?php echo round($ratingCollection,1);?><?php
                                 echo $this->__(' based on ');?><?php
                                  echo $reviewCount; ?><?php
                                   echo $this->__(' rating[s]');?></p>
                                <?php }
                                 else { ?>

                                <span class="all_reviews_details_wr">
                                    <p class="all_reviews_block">
                                     <label class="all_review_rating" style="width:0%;"></label>
                                        </p>
                                </span>
                                </span>
                            <?php } } ?>
                </div>
                  <?php
                /**
                 * Facebook, Twitter, Google Plus, Linked In Page link
                 */?>
                 <div class="social-media-wrapper">
                <?php
                /**
                 * Check the id is not empty of the social sharings like
                 * linked in
                 * Facebook
                 * Twitter
                 * Google Plus
                 * if they are not empty display their title with links
                 */
                if($sellerPage->getLinkedId() != ''){?>
                <a href="<?php echo $sellerPage->getLinkedId(); ?>" target="_blank" title="<?php
                echo $this->__('Instagram') ?>" class="instagram"><img src="http://148.251.126.204/~grotto/media/wysiwyg/instagram_circle.png" /></a>
                <?php } ?>
                <?php if($sellerPage->getFacebookId() != ''){?>
                <a href="<?php echo $sellerPage->getFacebookId(); ?>" target="_blank" title="<?php
                 echo $this->__('Facebook') ?>" class="facebook">&nbsp;</a>
                <?php } ?>
                <?php if($sellerPage->getTwitterId() != ''){?>
                <a href="<?php echo $sellerPage->getTwitterId();?>" target="_blank" title="<?php
                 echo $this->__('twitter') ?>" class="twitter">&nbsp;</a>
                <?php } ?>
                <?php if($sellerPage->getGoogleId() != ''){?>
                <a href="<?php echo $sellerPage->getGoogleId();?>" target="_blank" title="<?php
                echo $this->__('Pinterest') ?>" class="pinterest"><img src="http://148.251.126.204/~grotto/media/wysiwyg/pinterest-cir.png" /></a>
                <?php } ?>
                </div>
                </div>

    </div>
   </div>
   </div>
    <div class="clear"></div>
    <!--<div class="mp_profiles_desc">
    <p class="mp_profiles_desc"><?php /*echo $sellerPage->getDescription(); */?></p>
    </div>-->
    <div class="m_profiles_desc_cont">
       <h1 class="m_brand_name"><?php echo $sellerPage->getStoreTitle(); ?></h1>
       <p class="m_brand_location"><?php if(!empty($sellState)): ?><span><?php echo $sellState;?></span>, <?php endif;?><span><?php echo $countries[$sellCountry];?></span></p>
    <p class="m_profiles_desc"><?php echo $sellerPage->getDescription(); ?></p>
    </div>
   <?php 
/**
 * Two column block
 */
?>
