/* USE THIS FUNCTION TO EXECUTE SCRIPTS AFTER THE AJAX LOAD
 * IN THIS CASE, WE RECREATE THE EXPAND /  COLLAPSE PATTERN USED IN THE RWD THEME
 * BECAUSE IT IS IMPLEMENTED WITHOUT USING A LIVE FUNCTION SO IT NEEDS TO BE RECREATED EACH TIME THE AJAX IS LOADED
 */


function afterAjaxReload(){
    
    
    
   /* do something... */
    
}